365: enhancement: Ajout de l'option pour ajouter des img background d…
quadproduction/openpype-custom-plugins pull request #63
Opened 2024-07-15 13:16 UTC by hfarre

…ans la cam blender, et modification des précédentes fonctions pour modifier la dernière img bakcground loaded.

Fix quadproduction/issues#365

2024-08-13 15:29 UTC, hfarre commented
> Dernier point: Pourquoi avoir ajouter les fichiers `add_* `qui semblent être des copies des fichiers `import_*`
@BenSouchet 
Le import permet uniquement d'importer un background image s'il n'y en a pas ou bien d'ecraser le dernier importé.
Le add lui, permet de d'ajouter des background image en plus des existantes

2024-08-13 15:35 UTC, hfarre commented
> Il semble qu'il y ai du code commun avec cette PR: #64

Yes, je viens de le clean

2024-08-14 09:28 UTC, BenSouchet requested changes
Y aurait-il un moyen d'ajouter dans le dict `options` un bool nommé `replace_last`, qui si il est a True remplace  et sinon ajoute.

Comme ça aucune duplication de code juste un `if `a ajouter

2024-08-14 09:33 UTC, hfarre commented
Je pense que c'est une piste, mais comment lui fournir c'est là le soucis
Car dans le Loader, un bouton fait une action, et chaque bouton doit avoir son .py perso
![image](https://github.com/user-attachments/assets/6ae616b5-edc6-42c5-b961-7d1a6da7faaa)

Je vais etudier la question, mais là à chaud, je ne vois comment donner 2 comportements différents au même bouton

2024-08-14 09:39 UTC, BenSouchet commented
> Je pense que c'est une piste, mais comment lui fournir c'est là le soucis Car dans le Loader, un bouton fait une action, et chaque bouton doit avoir son .py perso ![image](https://private-user-images.githubusercontent.com/139864808/357758864-6ae616b5-edc6-42c5-b961-7d1a6da7faaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjg0MzUsIm5iZiI6MTcyMzYyODEzNSwicGF0aCI6Ii8xMzk4NjQ4MDgvMzU3NzU4ODY0LTZhZTYxNmI1LWVkYzYtNDJjNS1iOTYxLTdkMWE2ZGE3ZmFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTM1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGQzZmRlOWViODU3MzBhODQ4ZTU1MDdmMTQ2NjZlNzAwYWY5MDNmNWQ5OGVkNWNjNTVjNDdmMDlkOTU5NjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvWWoAqrsH669hd0__Z8esDDLUHKo-h6rXE25LJtjic)
> 
> Je vais etudier la question, mais là à chaud, je ne vois comment donner 2 comportements différents au même bouton

Est-ce lié au fichiers ou aux classes python qu'il trouve? Genre, pouvons-nous mettre deux action dans un seul fichier?
Si oui alors faire une fonction située en dehors des classes dans le même fichier et les deux classes (une pour le `Add` et une pour le `load/replace`) appel la fonction avec un bool qui est soit à `true` pour un replace soit `false` pour un add

2024-08-14 09:45 UTC, hfarre commented
> > Je pense que c'est une piste, mais comment lui fournir c'est là le soucis Car dans le Loader, un bouton fait une action, et chaque bouton doit avoir son .py perso ![image](https://private-user-images.githubusercontent.com/139864808/357758864-6ae616b5-edc6-42c5-b961-7d1a6da7faaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjg0MzUsIm5iZiI6MTcyMzYyODEzNSwicGF0aCI6Ii8xMzk4NjQ4MDgvMzU3NzU4ODY0LTZhZTYxNmI1LWVkYzYtNDJjNS1iOTYxLTdkMWE2ZGE3ZmFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTM1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGQzZmRlOWViODU3MzBhODQ4ZTU1MDdmMTQ2NjZlNzAwYWY5MDNmNWQ5OGVkNWNjNTVjNDdmMDlkOTU5NjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvWWoAqrsH669hd0__Z8esDDLUHKo-h6rXE25LJtjic)
> > Je vais etudier la question, mais là à chaud, je ne vois comment donner 2 comportements différents au même bouton
> 
> Est-ce lié au fichiers ou aux classes python qu'il trouve? Genre, pouvons-nous mettre deux actions dans un seul fichier? Si oui alors faire une fonction située en dehors des classes dans le même fichier et les deux classes (une pour le `Add` et une pour le `load/replace`) appel la fonction avec un bool qui est soit à `true` pour un replace soit `false` pour un add

En effet, on peut mettre les 2 classes (add et import) dans le même .py, ça semble les reconnaitre et créer 2 bouton distinct.
Je vais tenter un truc et j'te tiens au jus

2024-08-14 09:48 UTC, BenSouchet commented
@hfarre Hésite pas à demander conseils à @ccaillot pour toute éventuel question pour simplifier ou réduire les redondances 😉

2024-08-14 12:54 UTC, hfarre commented
> @hfarre Hésite pas à demander conseils à @ccaillot pour toute éventuel question pour simplifier ou réduire les redondances 😉

C'est good je pense ! En effet on pouvait bien retrecir le code et optimiser
J'en ai profité pour mettre de plus jolies icones :
![image](https://github.com/user-attachments/assets/adbc61cd-23d2-4f8a-a9f7-4fc27706de58)

2024-08-14 13:14 UTC, BenSouchet commented
Top! Dernier point j'aurais plutôt nommé l'argument bool `replace_last_bg` et ensuite j'aurais fait:
```python
if replace_last and len(camera.data.background_images):
    background = camera.data.background_images[-1]
else:
    background = camera.data.background_images.new()
```

2024-08-19 14:05 UTC, merged